import { useState } from "react";

import classes from "./List.module.css";

const employeeData = [
  {
    name: "강미현",
    lastName: "Kang",
    firstName: "Mihyun",
    department: "직영본부 운영1팀 강남역",
    position: "점장",
    yumId: "YmI3328",
  },
  {
    name: "강병주",
    lastName: "Kang",
    firstName: "Byungjoo",
    department: "직영본부 운영1팀 수원역광장",
    position: "점장",
    yumId: "DmS1340",
  },
  {
    name: "강성권",
    lastName: "Kang",
    firstName: "Sungkwon",
    department: "직영본부 운영2팀 김포장기역",
    position: "점장",
    yumId: "TmS5874",
  },
  {
    name: "강성주",
    lastName: "강",
    firstName: "성주",
    department: "직영본부 운영2팀 주엽",
    position: "부점장",
    yumId: "TmO8410",
  },
  {
    name: "강수경",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "강영정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 사가정",
    position: "QL",
    yumId: "EuI7393",
  },
  {
    name: "강원식",
    lastName: "Kang",
    firstName: "Wonshik",
    department: "직영본부 운영1팀 강남고속터미널",
    position: "점장",
    yumId: "UmI1591",
  },
  {
    name: "강유리",
    lastName: "Kang",
    firstName: "Yuri",
    department: "직영본부 운영1팀 덕소",
    position: "점장",
    yumId: "UmO5331",
  },
  {
    name: "강인구",
    lastName: "Kang",
    firstName: "Ingu",
    department: "직영본부 운영1팀 용인수지",
    position: "점장",
    yumId: "VmQ2570",
  },
  {
    name: "강지수",
    lastName: "Kang",
    firstName: "Jisoo",
    department: "직영본부 운영1팀 속초DI",
    position: "점장",
    yumId: "KmB4414",
  },
  {
    name: "고동지",
    lastName: "고",
    firstName: "동지",
    department: "직영본부 운영2팀 용산아이파크몰",
    position: "부점장",
    yumId: "OmA1162",
  },
  {
    name: "고은아",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 진접",
    position: "부점장",
    yumId: "",
  },
  {
    name: "고은영",
    lastName: "Ko",
    firstName: "Eunyoung",
    department: "직영본부 운영3팀",
    position: "Area Coach",
    yumId: "eak9303",
  },
  {
    name: "고은진",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 진접",
    position: "QL",
    yumId: "",
  },
  {
    name: "고해현",
    lastName: "Go",
    firstName: "Haehyun",
    department: "직영본부 운영2팀 사당역",
    position: "부점장",
    yumId: "hbg3770",
  },
  {
    name: "공도현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 원주단계DT",
    position: "QL",
    yumId: "RuG5310",
  },
  {
    name: "공라윤",
    lastName: "",
    firstName: "",
    department: "HR본부 피플팀",
    position: "0",
    yumId: "",
  },
  {
    name: "곽영범",
    lastName: "Kwak",
    firstName: "Youngbeom",
    department: "직영본부 운영2팀 화곡역",
    position: "점장",
    yumId: "AmJ6098",
  },
  {
    name: "곽은화",
    lastName: "곽",
    firstName: "은화",
    department: "직영본부 운영2팀 청계천",
    position: "부점장",
    yumId: "VmE5249",
  },
  {
    name: "구동회",
    lastName: "Ku",
    firstName: "Donghywe",
    department: "직영본부 운영3팀 부산서면",
    position: "점장",
    yumId: "QmW2435",
  },
  {
    name: "구여진",
    lastName: "Ku",
    firstName: "Yeojin",
    department: "직영본부 운영3팀 김해내동",
    position: "점장",
    yumId: "BmF8958",
  },
  {
    name: "구희경",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 창원상남동",
    position: "QL",
    yumId: "0",
  },
  {
    name: "국솔애",
    lastName: "국",
    firstName: "솔애",
    department: "직영본부 운영1팀 안양일번가",
    position: "부점장",
    yumId: "JmD6644",
  },
  {
    name: "국희현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 범어네거리",
    position: "QL",
    yumId: "UuE3151",
  },
  {
    name: "권기덕",
    lastName: "권",
    firstName: "기덕",
    department: "직영본부 운영1팀 영통씨네마",
    position: "부점장",
    yumId: "FmK5685",
  },
  {
    name: "권다은",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀",
    position: "0",
    yumId: "",
  },
  {
    name: "권민성",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "권민지",
    lastName: "권",
    firstName: "민지",
    department: "직영본부 운영1팀 강남구청역",
    position: "부점장",
    yumId: "PmX2970",
  },
  {
    name: "권보연",
    lastName: "권",
    firstName: "보연",
    department: "직영본부 운영1팀 망우동",
    position: "부점장",
    yumId: "CmS4600",
  },
  {
    name: "권오영",
    lastName: "Kwon",
    firstName: "Ohyoung",
    department: "직영본부 운영3팀 하단역",
    position: "점장",
    yumId: "VmT4810",
  },
  {
    name: "권우석",
    lastName: "권",
    firstName: "우석",
    department: "직영본부 운영2팀 김포한강",
    position: "부점장",
    yumId: "YbY4812",
  },
  {
    name: "권은초",
    lastName: "Kwon",
    firstName: "Euncho",
    department: "직영본부 운영2팀 여의도",
    position: "점장",
    yumId: "VmF4790",
  },
  {
    name: "권익빈",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "권지민",
    lastName: "권",
    firstName: "지민",
    department: "직영본부 운영2팀 김포장기역",
    position: "부점장",
    yumId: "JmJ5600",
  },
  {
    name: "권태용",
    lastName: "",
    firstName: "",
    department: "가맹본부  개발1팀",
    position: "0",
    yumId: "",
  },
  {
    name: "권현정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 광주충장로",
    position: "부점장",
    yumId: "",
  },
  {
    name: "권형진",
    lastName: "권",
    firstName: "형진",
    department: "직영본부 운영3팀 대구용산DT",
    position: "부점장",
    yumId: "FmO1029",
  },
  {
    name: "길예빈",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "길중일",
    lastName: "Gil",
    firstName: "Jungil",
    department: "직영본부 운영1팀",
    position: "Area Coach",
    yumId: "jyg1877",
  },
  {
    name: "김갑곤",
    lastName: "",
    firstName: "",
    department: "가맹본부  시설감리팀 영선파트",
    position: "0",
    yumId: "",
  },
  {
    name: "김강민",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 웅진플레이도시",
    position: "부점장",
    yumId: "FuW1980",
  },
  {
    name: "김경민",
    lastName: "",
    firstName: "",
    department: "직영본부 운영전략팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김경상",
    lastName: "김",
    firstName: "경상",
    department: "직영본부 운영1팀 원주단계DT",
    position: "부점장",
    yumId: "ImD9285",
  },
  {
    name: "김경오",
    lastName: "Kim",
    firstName: "Kyungoh",
    department: "직영본부 운영1팀 정자역",
    position: "점장",
    yumId: "EmA2945",
  },
  {
    name: "김경원",
    lastName: "Gim",
    firstName: "Gyeongwon",
    department: "직영본부 운영1팀 산본역",
    position: "부점장",
    yumId: "gdg5952",
  },
  {
    name: "김관범",
    lastName: "Kim",
    firstName: "Kwanbeom",
    department: "직영본부 운영1팀 일원동",
    position: "점장",
    yumId: "WmV7898",
  },
  {
    name: "김광우",
    lastName: "김",
    firstName: "광우",
    department: "직영본부 운영3팀 대전타임월드",
    position: "점장",
    yumId: "FmW2701",
  },
  {
    name: "김광희",
    lastName: "",
    firstName: "",
    department: "직영본부 운영전략팀 매장지원파트",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김규성",
    lastName: "김",
    firstName: "규성",
    department: "직영본부 운영3팀 청주메가폴리스",
    position: "부점장",
    yumId: "UmJ2682",
  },
  {
    name: "김근성",
    lastName: "Kim",
    firstName: "Geunsung",
    department: "직영본부 운영1팀 춘천이마트",
    position: "점장",
    yumId: "MmQ8056",
  },
  {
    name: "김나현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 검단",
    position: "QL",
    yumId: "0",
  },
  {
    name: "김남훈",
    lastName: "Kim",
    firstName: "Namhoon",
    department: "직영본부 운영1팀 원주단계DT",
    position: "점장",
    yumId: "ImR1500",
  },
  {
    name: "김다솔",
    lastName: "Kim",
    firstName: "Dasol",
    department: "직영본부 운영3팀 평택",
    position: "점장",
    yumId: "DmK9080",
  },
  {
    name: "김다영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 파주금촌",
    position: "QL",
    yumId: "",
  },
  {
    name: "김다혜",
    lastName: "Kim",
    firstName: "Dahye",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "NuH7868",
  },
  {
    name: "김다희",
    lastName: "",
    firstName: "",
    department: "직영본부 운영전략팀 매장지원파트",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김도은",
    lastName: "Kim",
    firstName: "Doeun",
    department: "직영본부 운영3팀 세종이마트",
    position: "점장",
    yumId: "RmG1115",
  },
  {
    name: "김동한",
    lastName: "",
    firstName: "",
    department: "경영본부 전략기획팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김동호",
    lastName: "김",
    firstName: "동호",
    department: "직영본부 운영2팀 구로디지털2",
    position: "부점장",
    yumId: "EmQ2476",
  },
  {
    name: "김두진",
    lastName: "김",
    firstName: "두진",
    department: "직영본부 운영2팀 숙대입구",
    position: "부점장",
    yumId: "QmT7180",
  },
  {
    name: "김령아",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "김문현",
    lastName: "Kim",
    firstName: "Moonhyun",
    department: "직영본부 운영3팀 청주사창사거리",
    position: "점장",
    yumId: "JmM9646",
  },
  {
    name: "김미애",
    lastName: "김",
    firstName: "미애",
    department: "직영본부 운영1팀 노원역",
    position: "부점장",
    yumId: "FmE8737",
  },
  {
    name: "김민경",
    lastName: "Kim",
    firstName: "Minkyung",
    department: "직영본부 운영3팀 칠곡3지구",
    position: "점장",
    yumId: "ImJ5307",
  },
  {
    name: "김민성",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 일산후곡",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김민영",
    lastName: "Kim",
    firstName: "Minyoung",
    department: "직영본부 운영1팀 용인보정",
    position: "점장",
    yumId: "WmI3422",
  },
  {
    name: "김민정",
    lastName: "김",
    firstName: "민정",
    department: "직영본부 운영3팀 유성온천",
    position: "부점장",
    yumId: "SmY4257",
  },
  {
    name: "김민호",
    lastName: "",
    firstName: "",
    department: "가맹본부  시설감리팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김방실",
    lastName: "",
    firstName: "",
    department: "가맹본부  시설감리팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김병주",
    lastName: "김",
    firstName: "병주",
    department: "직영본부 운영3팀 범어네거리",
    position: "부점장",
    yumId: "RmW9553",
  },
  {
    name: "김병직",
    lastName: "김",
    firstName: "병직",
    department: "직영본부 운영1팀 안산고잔",
    position: "점장",
    yumId: "QmC1051",
  },
  {
    name: "김보라",
    lastName: "김",
    firstName: "보라",
    department: "직영본부 운영3팀 제주서귀포DI",
    position: "부점장",
    yumId: "RmR4220",
  },
  {
    name: "김보령",
    lastName: "",
    firstName: "",
    department: "HR본부 피플팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "김보미",
    lastName: "Kim",
    firstName: "Bomi",
    department: "직영본부 운영3팀 하단역",
    position: "부점장",
    yumId: "bbk6527",
  },
  {
    name: "김상기",
    lastName: "",
    firstName: "",
    department: "경영본부 IT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김상명",
    lastName: "김",
    firstName: "상명",
    department: "직영본부 운영1팀 의정부엔터",
    position: "부점장",
    yumId: "LmR2085",
  },
  {
    name: "김새봄",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "QL",
    yumId: "0",
  },
  {
    name: "김서현",
    lastName: "김",
    firstName: "서현",
    department: "직영본부 운영1팀 명일DI",
    position: "부점장",
    yumId: "YmE1522",
  },
  {
    name: "김선영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천공항교통센터",
    position: "부점장",
    yumId: "BuC5791",
  },
  {
    name: "김선은",
    lastName: "",
    firstName: "",
    department: "마케팅본부 FIT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김성용",
    lastName: "Kim",
    firstName: "Sungyong",
    department: "직영본부 운영1팀 양재동",
    position: "점장",
    yumId: "VmY7224",
  },
  {
    name: "김성태",
    lastName: "김",
    firstName: "성태",
    department: "직영본부 운영2팀 연신내역",
    position: "부점장",
    yumId: "TmP1240",
  },
  {
    name: "김성훈",
    lastName: "",
    firstName: "",
    department: "가맹본부",
    position: "CDO",
    yumId: "",
  },
  {
    name: "김세림",
    lastName: "Kim",
    firstName: "Serim",
    department: "직영본부 운영2팀 신정네거리역",
    position: "부점장",
    yumId: "skk7913",
  },
  {
    name: "김세원",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 충무로역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김세은",
    lastName: "Kim",
    firstName: "Seeun",
    department: "직영본부 운영2팀 부천중동",
    position: "점장",
    yumId: "BmL4977",
  },
  {
    name: "김소연",
    lastName: "",
    firstName: "",
    department: "HR본부 EHS팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김소영",
    lastName: "Kim",
    firstName: "Soyoung",
    department: "미반영그룹",
    position: "0",
    yumId: "LmT2100",
  },
  {
    name: "김송이",
    lastName: "김",
    firstName: "송이",
    department: "직영본부 운영2팀 김포",
    position: "부점장",
    yumId: "HmG4859",
  },
  {
    name: "김수민",
    lastName: "김",
    firstName: "수민",
    department: "직영본부 운영3팀 경성대",
    position: "부점장",
    yumId: "BmN6896",
  },
  {
    name: "김수연",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 파주문산",
    position: "QL",
    yumId: "",
  },
  {
    name: "김수현",
    lastName: "",
    firstName: "",
    department: "HR본부",
    position: "본부장/CPO",
    yumId: "",
  },
  {
    name: "김승연",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 역삼역",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "김승현",
    lastName: "김",
    firstName: "승현",
    department: "직영본부 운영1팀 의정부민락",
    position: "점장",
    yumId: "DmX3766",
  },
  {
    name: "김승환",
    lastName: "김",
    firstName: "승환",
    department: "직영본부 운영2팀 행신역",
    position: "부점장",
    yumId: "CmT9070",
  },
  {
    name: "김시연",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "김신영",
    lastName: "Kim",
    firstName: "Shinyoung",
    department: "직영본부 운영2팀 파주운정DI",
    position: "점장",
    yumId: "KmR7178",
  },
  {
    name: "김연수",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 수원인계DT",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김연일",
    lastName: "",
    firstName: "",
    department: "가맹본부",
    position: "본부장/COO",
    yumId: "",
  },
  {
    name: "김연주",
    lastName: "김",
    firstName: "연주",
    department: "직영본부 운영1팀 용인수지",
    position: "부점장",
    yumId: "NmO3376",
  },
  {
    name: "김연진",
    lastName: "Kim",
    firstName: "Yeonjin",
    department: "직영본부 운영3팀 구미옥계",
    position: "점장",
    yumId: "QmH2294",
  },
  {
    name: "김예지",
    lastName: "Kim",
    firstName: "Yeji",
    department: "직영본부 운영3팀 동탄",
    position: "점장",
    yumId: "SmS9217",
  },
  {
    name: "김요한",
    lastName: "김",
    firstName: "요한",
    department: "직영본부 운영3팀 침산네거리",
    position: "부점장",
    yumId: "LmP7021",
  },
  {
    name: "김용성",
    lastName: "",
    firstName: "",
    department: "마케팅본부 FIT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김용진",
    lastName: "",
    firstName: "",
    department: "가맹본부  시설감리팀 영선파트",
    position: "0",
    yumId: "",
  },
  {
    name: "김용훈",
    lastName: "Kim",
    firstName: "Youghun",
    department: "직영본부 운영2팀 목동사거리",
    position: "점장",
    yumId: "ykk6886",
  },
  {
    name: "김웅기",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "김원우",
    lastName: "Kim",
    firstName: "Wonwoo",
    department: "직영본부 운영1팀 서현역",
    position: "점장",
    yumId: "UmP5253",
  },
  {
    name: "김윤아",
    lastName: "Kim",
    firstName: "Yoonah",
    department: "직영본부 운영1팀 학동역2",
    position: "점장",
    yumId: "VqX7882",
  },
  {
    name: "김윤화",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 계산동",
    position: "QL",
    yumId: "",
  },
  {
    name: "김은별",
    lastName: "Kim",
    firstName: "Eunbyeol",
    department: "직영본부 운영3팀 제주시청",
    position: "부점장",
    yumId: "edk3769",
  },
  {
    name: "김은중",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 안성중앙로",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김은진",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 수영역",
    position: "QL",
    yumId: "",
  },
  {
    name: "김이근",
    lastName: "Kim",
    firstName: "Yigeun",
    department: "직영본부 운영2팀 웅진플레이도시",
    position: "점장",
    yumId: "RmY4060",
  },
  {
    name: "김재원",
    lastName: "김",
    firstName: "재원",
    department: "직영본부 운영3팀 제주시청",
    position: "부점장",
    yumId: "SbH7610",
  },
  {
    name: "김재호",
    lastName: "",
    firstName: "",
    department: "경영본부 IT팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "김재훈",
    lastName: "Kim",
    firstName: "Jaehoon",
    department: "직영본부 운영1팀 안산중앙",
    position: "점장",
    yumId: "EmV6850",
  },
  {
    name: "김정숙",
    lastName: "Kim",
    firstName: "Jeongsook",
    department: "직영본부 운영3팀 천안두정",
    position: "점장",
    yumId: "jqk4178",
  },
  {
    name: "김정연",
    lastName: "김",
    firstName: "정연",
    department: "직영본부 운영2팀 전농동",
    position: "부점장",
    yumId: "WmS2633",
  },
  {
    name: "김정훈",
    lastName: "",
    firstName: "",
    department: "마케팅본부 브랜드MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김정희",
    lastName: "Kim",
    firstName: "Jeonghee",
    department: "직영본부 운영1팀 대치동",
    position: "점장",
    yumId: "UmP5619",
  },
  {
    name: "김종성",
    lastName: "김",
    firstName: "종성",
    department: "직영본부 운영3팀 부산서면",
    position: "부점장",
    yumId: "AmR4284",
  },
  {
    name: "김종철",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "김좌진",
    lastName: "Kim",
    firstName: "JwaJin",
    department: "직영본부 운영1팀 망우동",
    position: "점장",
    yumId: "TmA9727",
  },
  {
    name: "김지영",
    lastName: "Kim",
    firstName: "Jiyoung",
    department: "직영본부 운영2팀 행신역",
    position: "점장",
    yumId: "OmY2376",
  },
  {
    name: "김지우",
    lastName: "김",
    firstName: "지우",
    department: "직영본부 운영2팀 명지대",
    position: "부점장",
    yumId: "CmP3634",
  },
  {
    name: "김지운",
    lastName: "김",
    firstName: "지운",
    department: "직영본부 운영3팀 광주터미널유스퀘어",
    position: "부점장",
    yumId: "ImF3505",
  },
  {
    name: "김지율",
    lastName: "Kim",
    firstName: "Jiyul",
    department: "직영본부 운영3팀 영남대",
    position: "점장",
    yumId: "JmT6087",
  },
  {
    name: "김지은",
    lastName: "Kim",
    firstName: "Jieun",
    department: "직영본부 운영1팀 안산고잔",
    position: "부점장",
    yumId: "GmX4456",
  },
  {
    name: "김지현",
    lastName: "Kim",
    firstName: "Jihyun",
    department: "직영본부 운영2팀 부천역",
    position: "점장",
    yumId: "QmB6617",
  },
  {
    name: "김지훈",
    lastName: "",
    firstName: "",
    department: "직영본부",
    position: "본부장/CSO",
    yumId: "",
  },
  {
    name: "김진경",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 부천상동HP",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김진규",
    lastName: "KIM",
    firstName: "Jinkyu",
    department: "직영본부 운영2팀 간석HP",
    position: "점장",
    yumId: "AmJ8630",
  },
  {
    name: "김진서",
    lastName: "김",
    firstName: "진서",
    department: "직영본부 운영3팀 황금동",
    position: "부점장",
    yumId: "WmF4630",
  },
  {
    name: "김진아",
    lastName: "Kim",
    firstName: "Jina",
    department: "직영본부 운영1팀 정자역",
    position: "부점장",
    yumId: "jbk7815",
  },
  {
    name: "김진태",
    lastName: "Kim",
    firstName: "Jintae",
    department: "직영본부 운영2팀 상수역",
    position: "부점장",
    yumId: "jbk4045",
  },
  {
    name: "김진화",
    lastName: "Kim",
    firstName: "Jinhwa",
    department: "직영본부 운영1팀 미사역",
    position: "부점장",
    yumId: "jdk8822",
  },
  {
    name: "김창훈",
    lastName: "",
    firstName: "",
    department: "가맹본부  개발2팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "김채연",
    lastName: "",
    firstName: "",
    department: "미반영그룹",
    position: "0",
    yumId: "LmR7647",
  },
  {
    name: "김총",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "김태석",
    lastName: "Kim",
    firstName: "TaeSeok",
    department: "직영본부 운영2팀 보라매",
    position: "점장",
    yumId: "GmR9309",
  },
  {
    name: "김태연",
    lastName: "김",
    firstName: "태연",
    department: "직영본부 운영2팀 홍익대",
    position: "부점장",
    yumId: "XmD5771",
  },
  {
    name: "김태현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천송도",
    position: "부점장",
    yumId: "",
  },
  {
    name: "김태훈",
    lastName: "Kim",
    firstName: "Taehoon",
    department: "직영본부 운영3팀 대전시청역",
    position: "부점장",
    yumId: "tdk6086",
  },
  {
    name: "김태희",
    lastName: "Kim",
    firstName: "Taehee",
    department: "직영본부 운영2팀 발산역",
    position: "점장",
    yumId: "KmN8024",
  },
  {
    name: "김하늘",
    lastName: "Kim",
    firstName: "Haneul",
    department: "직영본부 운영1팀 개롱역",
    position: "부점장",
    yumId: "hdk2159",
  },
  {
    name: "김한나",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 한국외대",
    position: "부점장",
    yumId: "RmP7024",
  },
  {
    name: "김현동",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 세종대",
    position: "QL",
    yumId: "KuP9901",
  },
  {
    name: "김현용",
    lastName: "김",
    firstName: "현용",
    department: "직영본부 운영1팀 성남태평",
    position: "부점장",
    yumId: "CmW2718",
  },
  {
    name: "김현지",
    lastName: "김",
    firstName: "현지",
    department: "직영본부 운영1팀 코엑스mall",
    position: "부점장",
    yumId: "KmS7839",
  },
  {
    name: "김현진",
    lastName: "",
    firstName: "",
    department: "마케팅본부 플랫폼MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김형남",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 청주수곡DT",
    position: "QL",
    yumId: "AuG3553",
  },
  {
    name: "김형찬",
    lastName: "kim",
    firstName: "hyoungchan",
    department: "직영본부 운영1팀",
    position: "Area Coach",
    yumId: "hdk7603",
  },
  {
    name: "김혜숙",
    lastName: "김",
    firstName: "혜숙",
    department: "직영본부 운영1팀 용인명지DT",
    position: "부점장",
    yumId: "JmL5393",
  },
  {
    name: "김혜영",
    lastName: "Kim",
    firstName: "Hyeyoung",
    department: "직영본부 운영3팀 아산터미널",
    position: "점장",
    yumId: "FqK8873",
  },
  {
    name: "김혜지",
    lastName: "김",
    firstName: "혜지",
    department: "직영본부 운영1팀 하남시청",
    position: "점장",
    yumId: "TmA6009",
  },
  {
    name: "김홍주",
    lastName: "Kim",
    firstName: "Hongjoo",
    department: "직영본부 운영2팀 신림역",
    position: "점장",
    yumId: "SbM8115",
  },
  {
    name: "김홍준",
    lastName: "Kim",
    firstName: "Hongjun",
    department: "직영본부 운영2팀 가산디지털",
    position: "부점장",
    yumId: "hdk4976",
  },
  {
    name: "김효상",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 신사역",
    position: "QL",
    yumId: "",
  },
  {
    name: "김효선",
    lastName: "",
    firstName: "",
    department: "마케팅본부 브랜드MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "김효연",
    lastName: "Kim",
    firstName: "Hyoyeon",
    department: "직영본부 운영3팀 광주터미널유스퀘어",
    position: "점장",
    yumId: "QmL2272",
  },
  {
    name: "김효영",
    lastName: "김",
    firstName: "효영",
    department: "직영본부 운영3팀 상인네거리",
    position: "부점장",
    yumId: "JmM2273",
  },
  {
    name: "김희선",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "QL",
    yumId: "",
  },
  {
    name: "김희웅",
    lastName: "Kim",
    firstName: "HeeWoong",
    department: "직영본부 운영2팀 충무로역",
    position: "점장",
    yumId: "JmK2530",
  },
  {
    name: "김희진",
    lastName: "김",
    firstName: "희진",
    department: "직영본부 운영1팀 춘천이마트",
    position: "부점장",
    yumId: "AmM2888",
  },
  {
    name: "남경문",
    lastName: "Nam",
    firstName: "Gyeongmoon",
    department: "직영본부 운영1팀 안양일번가",
    position: "점장",
    yumId: "HmO3349",
  },
  {
    name: "남경현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 안산중앙",
    position: "부점장",
    yumId: "",
  },
  {
    name: "남소령",
    lastName: "남",
    firstName: "소령",
    department: "직영본부 운영2팀 파주문산",
    position: "부점장",
    yumId: "TmP2184",
  },
  {
    name: "남수정",
    lastName: "",
    firstName: "",
    department: "HR본부 EHS팀",
    position: "0",
    yumId: "",
  },
  {
    name: "남호정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천청라",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "남효원",
    lastName: "",
    firstName: "",
    department: "HR본부 EHS팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "노연수",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 명지대",
    position: "부점장",
    yumId: "",
  },
  {
    name: "노우영",
    lastName: "No",
    firstName: "WooYoung",
    department: "직영본부 운영3팀 범어네거리",
    position: "점장",
    yumId: "FmG9230",
  },
  {
    name: "노지승",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 응암",
    position: "부점장",
    yumId: "",
  },
  {
    name: "도경언",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 황금동",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "도욱례",
    lastName: "도",
    firstName: "욱례",
    department: "직영본부 운영1팀 일원동",
    position: "부점장",
    yumId: "GmP3244",
  },
  {
    name: "마은영",
    lastName: "마",
    firstName: "은영",
    department: "직영본부 운영3팀 수영역",
    position: "부점장",
    yumId: "QmI7891",
  },
  {
    name: "마호재",
    lastName: "Ma",
    firstName: "Hojae",
    department: "직영본부 운영2팀",
    position: "Area Coach",
    yumId: "hym5207",
  },
  {
    name: "맹나연",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "",
  },
  {
    name: "문서진",
    lastName: "Moon",
    firstName: "Seojin",
    department: "직영본부 운영2팀 신촌역",
    position: "부점장",
    yumId: "sem4917",
  },
  {
    name: "문석진",
    lastName: "문",
    firstName: "석진",
    department: "직영본부 운영3팀 안성중앙로",
    position: "부점장",
    yumId: "ImV1002",
  },
  {
    name: "문승원",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천스퀘어원",
    position: "QL",
    yumId: "GuQ8349",
  },
  {
    name: "민규태",
    lastName: "민",
    firstName: "규태",
    department: "직영본부 운영3팀 창원더시티세븐",
    position: "점장",
    yumId: "SmG3988",
  },
  {
    name: "민재홍",
    lastName: "Min",
    firstName: "Jaehong",
    department: "직영본부 운영1팀 춘천석사",
    position: "점장",
    yumId: "ImF8723",
  },
  {
    name: "민재희",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 제주시청",
    position: "부점장",
    yumId: "PuU6606",
  },
  {
    name: "민한솔",
    lastName: "Min",
    firstName: "Hansol",
    department: "직영본부 운영1팀 용인에버랜드",
    position: "부점장",
    yumId: "hdm3884",
  },
  {
    name: "박관규",
    lastName: "Park",
    firstName: "KwanGyu",
    department: "직영본부 운영1팀 미금역",
    position: "점장",
    yumId: "SmF3812",
  },
  {
    name: "박근영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 원주단계DT",
    position: "부점장",
    yumId: "",
  },
  {
    name: "박나윤",
    lastName: "박",
    firstName: "나윤",
    department: "직영본부 운영1팀 속초DI",
    position: "부점장",
    yumId: "TmI8359",
  },
  {
    name: "박동진",
    lastName: "박",
    firstName: "동진",
    department: "직영본부 운영1팀 석촌역",
    position: "부점장",
    yumId: "GmY9140",
  },
  {
    name: "박명인",
    lastName: "",
    firstName: "",
    department: "경영본부 전략기획팀",
    position: "0",
    yumId: "",
  },
  {
    name: "박명희",
    lastName: "박",
    firstName: "명희",
    department: "직영본부 운영1팀 학동역2",
    position: "부점장",
    yumId: "FmE7060",
  },
  {
    name: "박미",
    lastName: "Park",
    firstName: "Mi",
    department: "직영본부 운영1팀 수원인계DT",
    position: "점장",
    yumId: "VmR9468",
  },
  {
    name: "박민규",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 중앙대",
    position: "QL",
    yumId: "",
  },
  {
    name: "박민기",
    lastName: "Park",
    firstName: "MinGi",
    department: "직영본부 운영1팀 서초우성",
    position: "점장",
    yumId: "TmK1619",
  },
  {
    name: "박민정",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "박병규",
    lastName: "Park",
    firstName: "ByungKyu",
    department: "직영본부 운영1팀 용인상현",
    position: "점장",
    yumId: "EmA8129",
  },
  {
    name: "박상우",
    lastName: "박",
    firstName: "상우",
    department: "직영본부 운영1팀 우이동",
    position: "부점장",
    yumId: "AmX9494",
  },
  {
    name: "박상태",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 의정부HP",
    position: "부점장",
    yumId: "",
  },
  {
    name: "박선정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 동탄",
    position: "QL",
    yumId: "",
  },
  {
    name: "박선화",
    lastName: "Park",
    firstName: "Sunhwa",
    department: "직영본부 운영1팀 하안동",
    position: "점장",
    yumId: "WmA8492",
  },
  {
    name: "박성민",
    lastName: "Park",
    firstName: "Sungmin",
    department: "직영본부 운영2팀 화정",
    position: "부점장",
    yumId: "sep8479",
  },
  {
    name: "박성진",
    lastName: "Park",
    firstName: "Sungjin",
    department: "직영본부 운영2팀 연신내역",
    position: "점장",
    yumId: "JmE9705",
  },
  {
    name: "박세진",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 전북도청",
    position: "QL",
    yumId: "0",
  },
  {
    name: "박세환",
    lastName: "Park",
    firstName: "Sehwan",
    department: "직영본부 운영1팀 의정부엔터",
    position: "점장",
    yumId: "HmV1259",
  },
  {
    name: "박소연",
    lastName: "Park",
    firstName: "Soyeon",
    department: "직영본부 운영3팀 청주수곡DT",
    position: "점장",
    yumId: "OmH5623",
  },
  {
    name: "박수아",
    lastName: "박",
    firstName: "수아",
    department: "직영본부 운영1팀 광장동",
    position: "부점장",
    yumId: "SmS6303",
  },
  {
    name: "박수진",
    lastName: "박",
    firstName: "수진",
    department: "직영본부 운영1팀 속초DI",
    position: "부점장",
    yumId: "SmA1240",
  },
  {
    name: "박수현",
    lastName: "박",
    firstName: "수현",
    department: "직영본부 운영3팀 천안쌍용",
    position: "부점장",
    yumId: "KmJ2800",
  },
  {
    name: "박순옥",
    lastName: "Park",
    firstName: "Soonok",
    department: "직영본부 운영1팀 서초우성",
    position: "부점장",
    yumId: "sdp9169",
  },
  {
    name: "박순자",
    lastName: "박",
    firstName: "순자",
    department: "직영본부 운영3팀 황금동",
    position: "부점장",
    yumId: "NmA8477",
  },
  {
    name: "박승진",
    lastName: "Park",
    firstName: "Seungjin",
    department: "직영본부 운영1팀 창동역",
    position: "점장",
    yumId: "skp5709",
  },
  {
    name: "박시연",
    lastName: "박",
    firstName: "시연",
    department: "직영본부 운영2팀 발산역",
    position: "부점장",
    yumId: "SbY1486",
  },
  {
    name: "박연경",
    lastName: "Park",
    firstName: "Yeonkyung",
    department: "직영본부 운영2팀 주엽",
    position: "부점장",
    yumId: "yep6601",
  },
  {
    name: "박영민",
    lastName: "Park",
    firstName: "YoungMin",
    department: "직영본부 운영3팀 침산네거리",
    position: "점장",
    yumId: "OmK5264",
  },
  {
    name: "박영숙",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 간석HP",
    position: "QL",
    yumId: "MuH6899",
  },
  {
    name: "박영은",
    lastName: "Park",
    firstName: "YoungEun",
    department: "직영본부 운영1팀 의정부HP",
    position: "점장",
    yumId: "ImA4812",
  },
  {
    name: "박윤서",
    lastName: "Park",
    firstName: "Yunseo",
    department: "직영본부 운영1팀 야탑역",
    position: "부점장",
    yumId: "yep6800",
  },
  {
    name: "박윤식",
    lastName: "",
    firstName: "",
    department: "마케팅본부 FIT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "박은지",
    lastName: "Park",
    firstName: "Eunji",
    department: "직영본부 운영3팀 대구문화동",
    position: "점장",
    yumId: "SmJ7746",
  },
  {
    name: "박일균",
    lastName: "Park",
    firstName: "Ilgyun",
    department: "직영본부 운영3팀 광주터미널유스퀘어",
    position: "부점장",
    yumId: "iep3798",
  },
  {
    name: "박장현",
    lastName: "박",
    firstName: "장현",
    department: "직영본부 운영2팀 인천송도",
    position: "부점장",
    yumId: "JmP4009",
  },
  {
    name: "박재현",
    lastName: "Park",
    firstName: "Jaehyeon",
    department: "직영본부 운영2팀 간석HP",
    position: "부점장",
    yumId: "jep1621",
  },
  {
    name: "박정현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 망우동",
    position: "QL",
    yumId: "EuB7382",
  },
  {
    name: "박종범",
    lastName: "박",
    firstName: "종범",
    department: "직영본부 운영3팀 청주수곡DT",
    position: "부점장",
    yumId: "BmI7389",
  },
  {
    name: "박종석",
    lastName: "박",
    firstName: "종석",
    department: "직영본부 운영2팀 응암",
    position: "부점장",
    yumId: "TmS2575",
  },
  {
    name: "박종훈",
    lastName: "박",
    firstName: "종훈",
    department: "직영본부 운영1팀 정자역",
    position: "부점장",
    yumId: "GmL1059",
  },
  {
    name: "박주희",
    lastName: "Park",
    firstName: "Joohee",
    department: "직영본부 운영3팀 황금동",
    position: "점장",
    yumId: "ImJ1945",
  },
  {
    name: "박지수",
    lastName: "Park",
    firstName: "Jisu",
    department: "직영본부 운영1팀 산본역",
    position: "부점장",
    yumId: "jep8658",
  },
  {
    name: "박지재",
    lastName: "Park",
    firstName: "Jijae",
    department: "직영본부 운영3팀 제주시청",
    position: "점장",
    yumId: "TmY7301",
  },
  {
    name: "박지혜",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "",
  },
  {
    name: "박지호",
    lastName: "박",
    firstName: "지호",
    department: "직영본부 운영3팀 서귀포중문DT",
    position: "부점장",
    yumId: "JmV1838",
  },
  {
    name: "박지훈",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀",
    position: "0",
    yumId: "",
  },
  {
    name: "박진우",
    lastName: "Park",
    firstName: "Jinwoo",
    department: "직영본부 운영2팀 용산아이파크몰",
    position: "점장",
    yumId: "GmJ5931",
  },
  {
    name: "박찬호",
    lastName: "박",
    firstName: "찬호",
    department: "직영본부 운영3팀 전주송천",
    position: "부점장",
    yumId: "CmD5742",
  },
  {
    name: "박창민",
    lastName: "Park",
    firstName: "Changmin",
    department: "직영본부 운영3팀 부산구서DT",
    position: "부점장",
    yumId: "cdp3383",
  },
  {
    name: "박철수",
    lastName: "Park",
    firstName: "Chulsoo",
    department: "직영본부 운영3팀 상인네거리",
    position: "점장",
    yumId: "KmE7087",
  },
  {
    name: "박철원",
    lastName: "박",
    firstName: "철원",
    department: "직영본부 운영2팀 목동",
    position: "부점장",
    yumId: "FmI2582",
  },
  {
    name: "박철진",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "박치호",
    lastName: "Park",
    firstName: "Chiho",
    department: "직영본부 운영2팀 미아사거리역",
    position: "점장",
    yumId: "AmX6325",
  },
  {
    name: "박한결",
    lastName: "",
    firstName: "",
    department: "HR본부 피플팀",
    position: "0",
    yumId: "",
  },
  {
    name: "박해양",
    lastName: "Park",
    firstName: "Haesoo",
    department: "직영본부 운영2팀 김포",
    position: "점장",
    yumId: "GmV3351",
  },
  {
    name: "박행혜",
    lastName: "Park",
    firstName: "Haenghye",
    department: "직영본부 운영2팀 상수역",
    position: "점장",
    yumId: "YmJ3168",
  },
  {
    name: "박현민",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 강남구청역",
    position: "점장",
    yumId: "KmP8025",
  },
  {
    name: "박현선",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천공항교통센터",
    position: "부점장",
    yumId: "XuS9214",
  },
  {
    name: "박현수",
    lastName: "박",
    firstName: "현수",
    department: "직영본부 운영2팀 돈암동1",
    position: "점장",
    yumId: "YmU5793",
  },
  {
    name: "박현진",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 코엑스mall",
    position: "부점장",
    yumId: "GmU9140hip7840",
  },
  {
    name: "박효순",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 신림역",
    position: "QL",
    yumId: "JuP4080",
  },
  {
    name: "박희진",
    lastName: "Park",
    firstName: "Heejin",
    department: "직영본부 운영2팀 주엽",
    position: "점장",
    yumId: "QmC2328",
  },
  {
    name: "방영훈",
    lastName: "Bang",
    firstName: "Yeonghoon",
    department: "직영본부 운영1팀 철산역",
    position: "점장",
    yumId: "XmJ3460",
  },
  {
    name: "방은경",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀",
    position: "0",
    yumId: "",
  },
  {
    name: "방준형",
    lastName: "",
    firstName: "",
    department: "마케팅본부 브랜드MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "배경록",
    lastName: "배",
    firstName: "경록",
    department: "직영본부 운영3팀 대전시청역",
    position: "부점장",
    yumId: "DmJ5190",
  },
  {
    name: "배기정",
    lastName: "Bae",
    firstName: "Kijeong",
    department: "직영본부 운영2팀 계산동",
    position: "점장",
    yumId: "KmT4721",
  },
  {
    name: "배승환",
    lastName: "Bae",
    firstName: "SeungHwan",
    department: "직영본부 운영1팀 구리돌다리",
    position: "점장",
    yumId: "WmI8544",
  },
  {
    name: "배예은",
    lastName: "Bae",
    firstName: "Yeeun",
    department: "직영본부 운영3팀 노은역",
    position: "부점장",
    yumId: "HmA4939",
  },
  {
    name: "배윤호",
    lastName: "배",
    firstName: "윤호",
    department: "미반영그룹",
    position: "0",
    yumId: "EmG6214",
  },
  {
    name: "배정빈",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 연제이마트",
    position: "QL",
    yumId: "",
  },
  {
    name: "배현",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "백민정",
    lastName: "",
    firstName: "",
    department: "마케팅본부",
    position: "본부장/CMO",
    yumId: "",
  },
  {
    name: "백유빈",
    lastName: "Baek",
    firstName: "Yoobin",
    department: "직영본부 운영1팀 우이동",
    position: "점장",
    yumId: "LmS5650",
  },
  {
    name: "백은정",
    lastName: "Baek",
    firstName: "EunJeong",
    department: "직영본부 운영2팀 전농동",
    position: "점장",
    yumId: "NmE6206",
  },
  {
    name: "백지언",
    lastName: "",
    firstName: "",
    department: "HR본부 피플팀",
    position: "0",
    yumId: "",
  },
  {
    name: "백지연",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 구로디지털2",
    position: "부점장",
    yumId: "VuL5711",
  },
  {
    name: "변충기",
    lastName: "Byun",
    firstName: "Chunggi",
    department: "직영본부 운영2팀",
    position: "Area Coach",
    yumId: "cyb9803",
  },
  {
    name: "봉윤영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 하안동",
    position: "QL",
    yumId: "OuX8541",
  },
  {
    name: "서상언",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "서상현",
    lastName: "Seo",
    firstName: "Sanghyun",
    department: "직영본부 운영1팀 개롱역",
    position: "점장",
    yumId: "OmK4847",
  },
  {
    name: "서영준",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 영남대",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "서예빈",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 서울대입구역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "서유정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 전북도청",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "서이슬",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 당산역",
    position: "부점장",
    yumId: "XuV8000",
  },
  {
    name: "서재련",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 노량진역",
    position: "QL",
    yumId: "",
  },
  {
    name: "서정일",
    lastName: "seo",
    firstName: "jeongil",
    department: "직영본부 운영1팀",
    position: "Area Coach",
    yumId: "cys4145",
  },
  {
    name: "서정혁",
    lastName: "Seo",
    firstName: "JeongHyeok",
    department: "직영본부 운영1팀",
    position: "Area Coach",
    yumId: "BbM1928",
  },
  {
    name: "서종명",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 부평역",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "서준석",
    lastName: "",
    firstName: "",
    department: "직영본부 운영전략팀",
    position: "0",
    yumId: "",
  },
  {
    name: "서지연",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 이수역",
    position: "부점장",
    yumId: "PuP5303",
  },
  {
    name: "서진주",
    lastName: "서",
    firstName: "진주",
    department: "직영본부 운영1팀 하안동",
    position: "부점장",
    yumId: "JmY5841",
  },
  {
    name: "서태호",
    lastName: "서",
    firstName: "태호",
    department: "직영본부 운영1팀 양재동",
    position: "부점장",
    yumId: "TmP9021",
  },
  {
    name: "선민서",
    lastName: "선",
    firstName: "민서",
    department: "직영본부 운영1팀 석계역",
    position: "부점장",
    yumId: "OmV1499",
  },
  {
    name: "선정미",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 부천역",
    position: "QL",
    yumId: "SuN6596",
  },
  {
    name: "성유석",
    lastName: "성",
    firstName: "유석",
    department: "직영본부 운영1팀 아주대",
    position: "부점장",
    yumId: "ImG1773",
  },
  {
    name: "성윤기",
    lastName: "성",
    firstName: "윤기",
    department: "직영본부 운영2팀 신촌역",
    position: "부점장",
    yumId: "JmL4444",
  },
  {
    name: "성정훈",
    lastName: "",
    firstName: "",
    department: "경영본부 전략기획팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "성종현",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "소만호",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 중앙대",
    position: "부점장",
    yumId: "GuW9032",
  },
  {
    name: "손규민",
    lastName: "손",
    firstName: "규민",
    department: "직영본부 운영1팀 의정부민락",
    position: "부점장",
    yumId: "PmF1673",
  },
  {
    name: "손미령",
    lastName: "",
    firstName: "",
    department: "마케팅본부 플랫폼MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "손미정",
    lastName: "손",
    firstName: "미정",
    department: "직영본부 운영3팀 부산지오21",
    position: "부점장",
    yumId: "PmS7803",
  },
  {
    name: "손민지",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 검단",
    position: "부점장",
    yumId: "MuW8505",
  },
  {
    name: "손영훈",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 부평역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "손윤진",
    lastName: "Son",
    firstName: "Yunjin",
    department: "직영본부 운영1팀 야탑역",
    position: "점장",
    yumId: "TmC7108",
  },
  {
    name: "손현우",
    lastName: "",
    firstName: "",
    department: "가맹본부  개발1팀",
    position: "0",
    yumId: "",
  },
  {
    name: "송경환",
    lastName: "Song",
    firstName: "Kyunghwan",
    department: "직영본부 운영1팀 먹골역",
    position: "점장",
    yumId: "HmJ2304",
  },
  {
    name: "송단비",
    lastName: "송",
    firstName: "단비",
    department: "직영본부 운영3팀 황금동",
    position: "부점장",
    yumId: "VmD3012",
  },
  {
    name: "송석제",
    lastName: "",
    firstName: "",
    department: "대외지원실",
    position: "0",
    yumId: "0",
  },
  {
    name: "송요인",
    lastName: "송",
    firstName: "요인",
    department: "직영본부 운영3팀 오산DT",
    position: "부점장",
    yumId: "SmI4090",
  },
  {
    name: "송용현",
    lastName: "Song",
    firstName: "Yonghyun",
    department: "직영본부 운영2팀 홍익대",
    position: "점장",
    yumId: "NmH3750",
  },
  {
    name: "송종석",
    lastName: "",
    firstName: "",
    department: "가맹본부  시설감리팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "송지우",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 침산네거리",
    position: "부점장",
    yumId: "",
  },
  {
    name: "송진주",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀",
    position: "0",
    yumId: "",
  },
  {
    name: "송태림",
    lastName: "Song",
    firstName: "Tairim",
    department: "직영본부 운영2팀 동대문",
    position: "점장",
    yumId: "OmX6030",
  },
  {
    name: "송현호",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 전주송천",
    position: "부점장",
    yumId: "",
  },
  {
    name: "신다경",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "",
  },
  {
    name: "신소라",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 천안두정",
    position: "QL",
    yumId: "",
  },
  {
    name: "신수빈",
    lastName: "신",
    firstName: "수빈",
    department: "직영본부 운영3팀 동탄",
    position: "부점장",
    yumId: "OmS5237",
  },
  {
    name: "신우성",
    lastName: "신",
    firstName: "우성",
    department: "직영본부 운영1팀 대치동",
    position: "부점장",
    yumId: "NmM4723",
  },
  {
    name: "신은수",
    lastName: "Shin",
    firstName: "Eunsoo",
    department: "직영본부 운영2팀 신정네거리역",
    position: "점장",
    yumId: "GmR4018",
  },
  {
    name: "신준희",
    lastName: "신",
    firstName: "준희",
    department: "직영본부 운영1팀 용인에버랜드",
    position: "부점장",
    yumId: "FmW5884",
  },
  {
    name: "신현정",
    lastName: "Shin",
    firstName: "HyunJeong",
    department: "직영본부 운영1팀 수원역사1",
    position: "점장",
    yumId: "CmL4226",
  },
  {
    name: "신혜정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 학동역2",
    position: "QL",
    yumId: "0",
  },
  {
    name: "신호상",
    lastName: "",
    firstName: "",
    department: "CEO",
    position: "CEO",
    yumId: "0",
  },
  {
    name: "심아름",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 야당역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "심윤서",
    lastName: "심",
    firstName: "윤서",
    department: "직영본부 운영2팀 마두역",
    position: "부점장",
    yumId: "VmS8648",
  },
  {
    name: "심은성",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 가산디지털",
    position: "QL",
    yumId: "",
  },
  {
    name: "심찬수",
    lastName: "",
    firstName: "",
    department: "HR본부 EHS팀",
    position: "0",
    yumId: "",
  },
  {
    name: "안병근",
    lastName: "Ahn",
    firstName: "ByungKun",
    department: "직영본부 운영1팀 코엑스mall",
    position: "점장",
    yumId: "HbD7206",
  },
  {
    name: "안병철",
    lastName: "",
    firstName: "",
    department: "경영본부 구매팀",
    position: "0",
    yumId: "",
  },
  {
    name: "안성원",
    lastName: "안",
    firstName: "성원",
    department: "직영본부 운영2팀 신금호역",
    position: "부점장",
    yumId: "DmW4097",
  },
  {
    name: "안수인",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 독산동",
    position: "QL",
    yumId: "CuD5450",
  },
  {
    name: "안연진",
    lastName: "Ahn",
    firstName: "Yeonjin",
    department: "직영본부 운영3팀 천안쌍용",
    position: "점장",
    yumId: "FmH6158",
  },
  {
    name: "안주훈",
    lastName: "",
    firstName: "",
    department: "직영본부 운영전략팀 매장지원파트",
    position: "부점장",
    yumId: "",
  },
  {
    name: "안현주",
    lastName: "Ahn",
    firstName: "Hyunjoo",
    department: "직영본부 운영3팀 경성대",
    position: "점장",
    yumId: "AmS4905",
  },
  {
    name: "양고은",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 상수역",
    position: "QL",
    yumId: "0",
  },
  {
    name: "양슬기",
    lastName: "",
    firstName: "",
    department: "직영본부 운영전략팀",
    position: "0",
    yumId: "",
  },
  {
    name: "양현권",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 유성온천",
    position: "QL",
    yumId: "0",
  },
  {
    name: "여용민",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "연규민",
    lastName: "연",
    firstName: "규민",
    department: "직영본부 운영3팀 청주사창사거리",
    position: "부점장",
    yumId: "DmM4670",
  },
  {
    name: "연상흠",
    lastName: "Yeon",
    firstName: "Sangheum",
    department: "직영본부 운영2팀 대학로",
    position: "부점장",
    yumId: "sgy1387",
  },
  {
    name: "염진수",
    lastName: "Yum",
    firstName: "Jinsoo",
    department: "직영본부 운영2팀 화정",
    position: "점장",
    yumId: "OmC5231",
  },
  {
    name: "오경미",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "오미연",
    lastName: "Oh",
    firstName: "Miyeon",
    department: "직영본부 운영3팀 부산장산역",
    position: "점장",
    yumId: "VmC9990",
  },
  {
    name: "오선미",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 명일DI",
    position: "QL",
    yumId: "",
  },
  {
    name: "오선혁",
    lastName: "오",
    firstName: "선혁",
    department: "직영본부 운영2팀 부천중동",
    position: "부점장",
    yumId: "DbY3032",
  },
  {
    name: "오세은",
    lastName: "Oh",
    firstName: "Seeun",
    department: "직영본부 운영3팀 천안터미널",
    position: "점장",
    yumId: "AmH7014",
  },
  {
    name: "오수경",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 하단역",
    position: "QL",
    yumId: "0",
  },
  {
    name: "오승훈",
    lastName: "",
    firstName: "",
    department: "마케팅본부 플랫폼MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "오은혜",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 수원역광장",
    position: "부점장",
    yumId: "BuE6587",
  },
  {
    name: "오장현",
    lastName: "Oh",
    firstName: "Janghyeon",
    department: "직영본부 운영2팀 염창역",
    position: "점장",
    yumId: "KiM6149",
  },
  {
    name: "오정아",
    lastName: "",
    firstName: "",
    department: "미반영그룹",
    position: "0",
    yumId: "",
  },
  {
    name: "오준영",
    lastName: "Oh",
    firstName: "Junyoung",
    department: "직영본부 운영2팀 파주금촌",
    position: "점장",
    yumId: "jeo4671",
  },
  {
    name: "오창경",
    lastName: "",
    firstName: "",
    department: "HR본부 EHS팀",
    position: "0",
    yumId: "",
  },
  {
    name: "오태영",
    lastName: "Oh",
    firstName: "Taeyoung",
    department: "직영본부 운영2팀 숙대입구",
    position: "점장",
    yumId: "PmH2478",
  },
  {
    name: "오현우",
    lastName: "",
    firstName: "",
    department: "마케팅본부 FIT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "오혜정",
    lastName: "OH",
    firstName: "HYEJUNG",
    department: "직영본부 운영전략팀",
    position: "0",
    yumId: "hao6240",
  },
  {
    name: "우민경",
    lastName: "우",
    firstName: "민경",
    department: "직영본부 운영1팀 미사역",
    position: "부점장",
    yumId: "KmO5057",
  },
  {
    name: "우지현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 상암DMC",
    position: "QL",
    yumId: "",
  },
  {
    name: "유다현",
    lastName: "유",
    firstName: "다현",
    department: "직영본부 운영1팀 사가정",
    position: "부점장",
    yumId: "PmU5301",
  },
  {
    name: "유승현",
    lastName: "Ryu",
    firstName: "Seunghyun",
    department: "직영본부 운영2팀 노량진역",
    position: "점장",
    yumId: "NmI2092",
  },
  {
    name: "유은재",
    lastName: "유",
    firstName: "은재",
    department: "직영본부 운영2팀 화곡역",
    position: "부점장",
    yumId: "RmY7863",
  },
  {
    name: "유정희",
    lastName: "Yoo",
    firstName: "Jeonghee",
    department: "직영본부 운영3팀 연제이마트",
    position: "점장",
    yumId: "QmF5882",
  },
  {
    name: "유주연",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천구월",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "유준상",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 광주용봉DT",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "유지수",
    lastName: "Yoo",
    firstName: "Jisoo",
    department: "직영본부 운영1팀 광장동",
    position: "점장",
    yumId: "DmE8252",
  },
  {
    name: "유지희",
    lastName: "유",
    firstName: "지희",
    department: "직영본부 운영2팀 중앙대",
    position: "부점장",
    yumId: "RmW8287",
  },
  {
    name: "유진아",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 위례중앙",
    position: "QL",
    yumId: "",
  },
  {
    name: "유채운",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 평택",
    position: "부점장",
    yumId: "",
  },
  {
    name: "육태헌",
    lastName: "Yook",
    firstName: "Taeheon",
    department: "직영본부 운영1팀 관양1",
    position: "점장",
    yumId: "tgy1530",
  },
  {
    name: "윤단성",
    lastName: "윤",
    firstName: "단성",
    department: "직영본부 운영3팀 수영역",
    position: "점장",
    yumId: "BmD5721",
  },
  {
    name: "윤대용",
    lastName: "Yoon",
    firstName: "Daeyong",
    department: "직영본부 운영2팀 청계천",
    position: "점장",
    yumId: "SmE8790",
  },
  {
    name: "윤범석",
    lastName: "윤",
    firstName: "범석",
    department: "직영본부 운영2팀 일산후곡",
    position: "부점장",
    yumId: "QmK3349",
  },
  {
    name: "윤병륜",
    lastName: "Yoon",
    firstName: "Byungryun",
    department: "직영본부 운영2팀 왕십리역사",
    position: "점장",
    yumId: "FmF9519",
  },
  {
    name: "윤석찬",
    lastName: "Yoon",
    firstName: "Seokchan",
    department: "직영본부 운영2팀 야당역",
    position: "점장",
    yumId: "LmS6257",
  },
  {
    name: "윤성희",
    lastName: "Yoon",
    firstName: "Seonghee",
    department: "직영본부 운영2팀 부천중동",
    position: "부점장",
    yumId: "sgy6729",
  },
  {
    name: "윤소미",
    lastName: "Yun",
    firstName: "Somi",
    department: "직영본부 운영3팀 울산현대",
    position: "부점장",
    yumId: "sgy7969",
  },
  {
    name: "윤소임",
    lastName: "Yoon",
    firstName: "Soim",
    department: "직영본부 운영3팀 청주메가폴리스",
    position: "점장",
    yumId: "NmQ3631",
  },
  {
    name: "윤수빈",
    lastName: "Yoon",
    firstName: "Subin",
    department: "직영본부 운영2팀 부평역",
    position: "점장",
    yumId: "MmS4862",
  },
  {
    name: "윤시연",
    lastName: "Yoon",
    firstName: "Siyeon",
    department: "직영본부 운영3팀 부산지오21",
    position: "점장",
    yumId: "EmT8312",
  },
  {
    name: "윤은경",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 울산현대",
    position: "QL",
    yumId: "",
  },
  {
    name: "윤정은",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 구리돌다리",
    position: "QL",
    yumId: "0",
  },
  {
    name: "윤주식",
    lastName: "윤",
    firstName: "주식",
    department: "직영본부 운영3팀 상인네거리",
    position: "부점장",
    yumId: "TmQ8006",
  },
  {
    name: "윤지현",
    lastName: "윤",
    firstName: "지현",
    department: "직영본부 운영1팀 구리돌다리",
    position: "부점장",
    yumId: "HmE4480",
  },
  {
    name: "윤찬수",
    lastName: "윤",
    firstName: "찬수",
    department: "직영본부 운영2팀 미아사거리역",
    position: "부점장",
    yumId: "XbC8470",
  },
  {
    name: "윤현국",
    lastName: "Yoon",
    firstName: "Hyeonguk",
    department: "직영본부 운영1팀 역삼역",
    position: "점장",
    yumId: "AmP4489",
  },
  {
    name: "윤희정",
    lastName: "Yoon",
    firstName: "HeeJeong",
    department: "직영본부 운영2팀 인천구월",
    position: "점장",
    yumId: "VmG7812",
  },
  {
    name: "이가겸",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이가빈",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 강남고속터미널",
    position: "부점장",
    yumId: "MuF1933",
  },
  {
    name: "이겨레",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이경택",
    lastName: "이",
    firstName: "경택",
    department: "직영본부 운영3팀 칠곡3지구",
    position: "부점장",
    yumId: "RmW7619",
  },
  {
    name: "이경환",
    lastName: "이",
    firstName: "경환",
    department: "직영본부 운영3팀 창원상남동",
    position: "부점장",
    yumId: "SmT7122",
  },
  {
    name: "이경희",
    lastName: "이",
    firstName: "경희",
    department: "직영본부 운영3팀 김해내동",
    position: "부점장",
    yumId: "WmY9964",
  },
  {
    name: "이관도",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 천안터미널",
    position: "부점장",
    yumId: "KmE1614kil1281",
  },
  {
    name: "이관령",
    lastName: "Lee",
    firstName: "Gwanryeong",
    department: "직영본부 운영3팀 은행동1",
    position: "부점장",
    yumId: "gdl3530",
  },
  {
    name: "이광욱",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 동대문",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이규빈",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 둔촌동",
    position: "QL",
    yumId: "",
  },
  {
    name: "이나리",
    lastName: "Lee",
    firstName: "Nari",
    department: "직영본부 운영1팀 정자역",
    position: "부점장",
    yumId: "ndl1480",
  },
  {
    name: "이단비",
    lastName: "Lee",
    firstName: "Danbi",
    department: "직영본부 운영2팀 신림역",
    position: "부점장",
    yumId: "ddl7182",
  },
  {
    name: "이름",
    lastName: "",
    firstName: "",
    department: "소속",
    position: "직책",
    yumId: "0",
  },
  {
    name: "이미뢰",
    lastName: "Lee",
    firstName: "Miroe",
    department: "직영본부 운영2팀 검단",
    position: "부점장",
    yumId: "mel9273",
  },
  {
    name: "이미선",
    lastName: "Lee",
    firstName: "Misun",
    department: "직영본부 운영3팀 진주이마트",
    position: "점장",
    yumId: "CmS4741",
  },
  {
    name: "이미숙",
    lastName: "Lee",
    firstName: "Misook",
    department: "직영본부 운영3팀 사상역",
    position: "점장",
    yumId: "XmW4134",
  },
  {
    name: "이민구",
    lastName: "Lee",
    firstName: "Mingu",
    department: "직영본부 운영2팀 동인천이마트",
    position: "점장",
    yumId: "EmX1242",
  },
  {
    name: "이민성",
    lastName: "Lee",
    firstName: "Minsong",
    department: "직영본부 운영2팀 염창역",
    position: "부점장",
    yumId: "mdl8731",
  },
  {
    name: "이민재",
    lastName: "",
    firstName: "",
    department: "경영본부 구매팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이민정",
    lastName: "Lee",
    firstName: "Minjeong",
    department: "직영본부 운영1팀 용인명지DT",
    position: "점장",
    yumId: "KmF7300",
  },
  {
    name: "이민주",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 청계천",
    position: "QL",
    yumId: "0",
  },
  {
    name: "이민훈",
    lastName: "이",
    firstName: "민훈",
    department: "직영본부 운영3팀 광주수완",
    position: "점장",
    yumId: "UmB9457",
  },
  {
    name: "이병현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 계산동",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이보미",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 노량진역",
    position: "QL",
    yumId: "",
  },
  {
    name: "이보영",
    lastName: "",
    firstName: "",
    department: "미반영그룹",
    position: "0",
    yumId: "",
  },
  {
    name: "이상경",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 세종이마트",
    position: "부점장",
    yumId: "BmX7595sil5309",
  },
  {
    name: "이상기",
    lastName: "Lee",
    firstName: "Sangki",
    department: "직영본부 운영2팀 인천공항교통센터",
    position: "점장",
    yumId: "PmQ2611",
  },
  {
    name: "이상득",
    lastName: "이",
    firstName: "상득",
    department: "직영본부 운영1팀 안산고잔",
    position: "부점장",
    yumId: "JmY7565",
  },
  {
    name: "이상현",
    lastName: "Lee",
    firstName: "Sanghyun",
    department: "직영본부 운영3팀 포항양덕DT",
    position: "점장",
    yumId: "AmG7473",
  },
  {
    name: "이서아",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 영남대",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이서은",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 파주운정DI",
    position: "QL",
    yumId: "0",
  },
  {
    name: "이석제",
    lastName: "",
    firstName: "",
    department: "마케팅본부 플랫폼MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이선규",
    lastName: "Lee",
    firstName: "Sunkyu",
    department: "직영본부 운영1팀 잠실롯데월드",
    position: "점장",
    yumId: "PmV6226",
  },
  {
    name: "이선미",
    lastName: "이",
    firstName: "선미",
    department: "직영본부 운영1팀 춘천석사",
    position: "부점장",
    yumId: "ImV1644",
  },
  {
    name: "이선아",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 구미옥계",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이선의",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "QL",
    yumId: "",
  },
  {
    name: "이선희",
    lastName: "이",
    firstName: "선희",
    department: "직영본부 운영3팀 포항터미널",
    position: "점장",
    yumId: "JmI5333",
  },
  {
    name: "이성미",
    lastName: "Lee",
    firstName: "Sungmi",
    department: "직영본부 운영1팀 산본역",
    position: "점장",
    yumId: "QmE3758",
  },
  {
    name: "이성민",
    lastName: "Lee",
    firstName: "Sungmin",
    department: "직영본부 운영1팀 노원역",
    position: "점장",
    yumId: "ImV1765",
  },
  {
    name: "이성엽",
    lastName: "",
    firstName: "",
    department: "가맹본부  개발1팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이성주",
    lastName: "이",
    firstName: "성주",
    department: "직영본부 운영1팀 군포산본",
    position: "점장",
    yumId: "PmK4900",
  },
  {
    name: "이소라",
    lastName: "",
    firstName: "",
    department: "미반영그룹",
    position: "0",
    yumId: "",
  },
  {
    name: "이소진",
    lastName: "이",
    firstName: "소진",
    department: "직영본부 운영3팀 부산지오21",
    position: "부점장",
    yumId: "GmT9420",
  },
  {
    name: "이송현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 김해내동",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이수빈",
    lastName: "이",
    firstName: "수빈",
    department: "직영본부 운영3팀 천안두정",
    position: "부점장",
    yumId: "QmG1157",
  },
  {
    name: "이수지",
    lastName: "LEE",
    firstName: "SuJi",
    department: "직영본부 운영2팀",
    position: "Area Coach",
    yumId: "IbD2340",
  },
  {
    name: "이수현",
    lastName: "이",
    firstName: "수현",
    department: "직영본부 운영1팀 수원역사1",
    position: "부점장",
    yumId: "FmT4960",
  },
  {
    name: "이순호",
    lastName: "Lee",
    firstName: "Soonho",
    department: "직영본부 운영2팀 이수역",
    position: "점장",
    yumId: "OmS2844",
  },
  {
    name: "이슬기",
    lastName: "Lee",
    firstName: "Seulgi",
    department: "직영본부 운영1팀 성남태평",
    position: "점장",
    yumId: "WmQ7226",
  },
  {
    name: "이슬비",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 원주단계DT",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이승연",
    lastName: "이",
    firstName: "승연",
    department: "직영본부 운영2팀 광화문",
    position: "부점장",
    yumId: "RmN8355",
  },
  {
    name: "이승우",
    lastName: "이",
    firstName: "승우",
    department: "직영본부 운영3팀 사상역",
    position: "부점장",
    yumId: "MmX4603",
  },
  {
    name: "이승일",
    lastName: "Lee",
    firstName: "Seungil",
    department: "직영본부 운영1팀 위례중앙",
    position: "점장",
    yumId: "OmY1051",
  },
  {
    name: "이아진",
    lastName: "Lee",
    firstName: "AhJin",
    department: "직영본부 운영2팀 신촌역",
    position: "점장",
    yumId: "KmI6824",
  },
  {
    name: "이영미",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 창원상남동",
    position: "QL",
    yumId: "",
  },
  {
    name: "이영민",
    lastName: "Lee",
    firstName: "Youngmin",
    department: "직영본부 운영2팀",
    position: "Area Coach",
    yumId: "yil2642",
  },
  {
    name: "이영선",
    lastName: "이",
    firstName: "영선",
    department: "직영본부 운영1팀 사가정",
    position: "부점장",
    yumId: "VmK4466",
  },
  {
    name: "이예찬",
    lastName: "Lee",
    firstName: "Yechan",
    department: "직영본부 운영2팀 영등포역",
    position: "점장",
    yumId: "OjC7831",
  },
  {
    name: "이용우",
    lastName: "이",
    firstName: "용우",
    department: "직영본부 운영2팀 광화문",
    position: "부점장",
    yumId: "LmR9701",
  },
  {
    name: "이용희",
    lastName: "Lee",
    firstName: "Yonghee",
    department: "직영본부 운영1팀 영통씨네마",
    position: "점장",
    yumId: "RmY3692",
  },
  {
    name: "이원중",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 안산고잔",
    position: "QL",
    yumId: "",
  },
  {
    name: "이유진",
    lastName: "이",
    firstName: "유진",
    department: "직영본부 운영1팀 서울교대S",
    position: "점장",
    yumId: "RmI1957",
  },
  {
    name: "이윤성",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인하대",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이윤수",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인하대",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이윤표",
    lastName: "",
    firstName: "",
    department: "마케팅본부 플랫폼MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이은경",
    lastName: "Lee",
    firstName: "Eunkyung",
    department: "직영본부 운영2팀 부천상동HP",
    position: "점장",
    yumId: "BmT5848",
  },
  {
    name: "이은숙",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 신사역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이은영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 세종대",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이은주",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 미사역",
    position: "QL",
    yumId: "0",
  },
  {
    name: "이인기",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이인옥",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 당산역",
    position: "QL",
    yumId: "0",
  },
  {
    name: "이재석",
    lastName: "이",
    firstName: "재석",
    department: "직영본부 운영2팀 웅진플레이도시",
    position: "부점장",
    yumId: "MmE4505",
  },
  {
    name: "이재선",
    lastName: "Lee",
    firstName: "Jaesun",
    department: "직영본부 운영3팀 서귀포중문DT",
    position: "점장",
    yumId: "jdl6882",
  },
  {
    name: "이재오",
    lastName: "",
    firstName: "",
    department: "경영본부 구매팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이재익",
    lastName: "이",
    firstName: "재익",
    department: "직영본부 운영3팀 대구시지",
    position: "부점장",
    yumId: "SmQ8911",
  },
  {
    name: "이정",
    lastName: "이",
    firstName: "정",
    department: "직영본부 운영1팀 미사역",
    position: "부점장",
    yumId: "EmP2373",
  },
  {
    name: "이정제",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 영통씨네마",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이정헌",
    lastName: "Lee",
    firstName: "Jungheon",
    department: "직영본부 운영3팀 전주송천",
    position: "부점장",
    yumId: "jel1039",
  },
  {
    name: "이정호",
    lastName: "",
    firstName: "",
    department: "가맹본부  개발1팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "이정훈",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 내당동",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이제희",
    lastName: "",
    firstName: "",
    department: "경영본부 구매팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "이종관",
    lastName: "Lee",
    firstName: "Jongkwan",
    department: "직영본부 운영1팀 관양1",
    position: "부점장",
    yumId: "jel9563",
  },
  {
    name: "이종훈",
    lastName: "이",
    firstName: "종훈",
    department: "직영본부 운영3팀 포항양덕DT",
    position: "부점장",
    yumId: "TmD2770",
  },
  {
    name: "이종희",
    lastName: "",
    firstName: "",
    department: "가맹본부  시설감리팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이주경",
    lastName: "",
    firstName: "",
    department: "HR본부 준법감사팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "이주영",
    lastName: "이",
    firstName: "주영",
    department: "직영본부 운영2팀 목동",
    position: "부점장",
    yumId: "BbN2104",
  },
  {
    name: "이준영",
    lastName: "이",
    firstName: "준영",
    department: "직영본부 운영2팀 인천논현",
    position: "점장",
    yumId: "SmC5577",
  },
  {
    name: "이준형",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이준호",
    lastName: "Lee",
    firstName: "Junho",
    department: "직영본부 운영2팀 신금호역",
    position: "점장",
    yumId: "YmS4225",
  },
  {
    name: "이지수",
    lastName: "Lee",
    firstName: "Jisoo",
    department: "직영본부 운영3팀 당진",
    position: "점장",
    yumId: "DmE5715",
  },
  {
    name: "이지원",
    lastName: "",
    firstName: "",
    department: "경영본부 IT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이지유",
    lastName: "Lee",
    firstName: "Jiyu",
    department: "직영본부 운영2팀 목동",
    position: "점장",
    yumId: "jel3600",
  },
  {
    name: "이지은",
    lastName: "Lee",
    firstName: "Jieun",
    department: "직영본부 운영2팀 고대안암",
    position: "점장",
    yumId: "SmS4747",
  },
  {
    name: "이지헌",
    lastName: "이",
    firstName: "지헌",
    department: "직영본부 운영1팀 산본역",
    position: "부점장",
    yumId: "AmK8400",
  },
  {
    name: "이지호",
    lastName: "Lee",
    firstName: "Jiho",
    department: "직영본부 운영2팀 당산역",
    position: "점장",
    yumId: "LmG4151",
  },
  {
    name: "이지훈",
    lastName: "",
    firstName: "",
    department: "경영본부 구매팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이진규",
    lastName: "이",
    firstName: "진규",
    department: "직영본부 운영3팀 진주이마트",
    position: "부점장",
    yumId: "PmX1049",
  },
  {
    name: "이진우",
    lastName: "이",
    firstName: "진우",
    department: "직영본부 운영3팀 연제이마트",
    position: "부점장",
    yumId: "WmN1279",
  },
  {
    name: "이찬주",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천공항교통센터",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이창석",
    lastName: "Lee",
    firstName: "Changseok",
    department: "직영본부 운영1팀 둔촌동",
    position: "점장",
    yumId: "PmV8735",
  },
  {
    name: "이창훈",
    lastName: "",
    firstName: "",
    department: "경영본부",
    position: "본부장/CFO",
    yumId: "",
  },
  {
    name: "이태혁",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "이태호",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이한나",
    lastName: "이",
    firstName: "한나",
    department: "직영본부 운영3팀 대구용산DT",
    position: "점장",
    yumId: "EmG7460",
  },
  {
    name: "이현수",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 부산장산역",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "이현아",
    lastName: "Lee",
    firstName: "Hyeona",
    department: "직영본부 운영2팀 인천스퀘어원",
    position: "부점장",
    yumId: "hel8615",
  },
  {
    name: "이현진",
    lastName: "Lee",
    firstName: "Hyunjin",
    department: "직영본부 운영2팀 일산후곡",
    position: "점장",
    yumId: "EmH8790",
  },
  {
    name: "이형주",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 상암DMC",
    position: "점장",
    yumId: "IuP7208",
  },
  {
    name: "이혜빈",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "",
  },
  {
    name: "이혜영",
    lastName: "Lee",
    firstName: "Hyeyoung",
    department: "직영본부 운영1팀 서초동",
    position: "점장",
    yumId: "DmY6965",
  },
  {
    name: "이혜인",
    lastName: "이",
    firstName: "혜인",
    department: "직영본부 운영2팀 동인천이마트",
    position: "부점장",
    yumId: "FmI3600",
  },
  {
    name: "이환성",
    lastName: "Lee",
    firstName: "Hwansung",
    department: "직영본부 운영1팀 사가정",
    position: "점장",
    yumId: "GmE9747",
  },
  {
    name: "이환욱",
    lastName: "Lee",
    firstName: "Hawnwook",
    department: "직영본부 운영3팀 창원상남동",
    position: "부점장",
    yumId: "hdl8377",
  },
  {
    name: "임다슬",
    lastName: "임",
    firstName: "다슬",
    department: "직영본부 운영2팀 대학로",
    position: "점장",
    yumId: "TmS1455",
  },
  {
    name: "임동영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 하남시청",
    position: "부점장",
    yumId: "",
  },
  {
    name: "임명화",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 대전시청역",
    position: "QL",
    yumId: "0",
  },
  {
    name: "임명환",
    lastName: "Lim",
    firstName: "Myunghwan",
    department: "직영본부 운영1팀 중계은행사거리",
    position: "점장",
    yumId: "GmR9849",
  },
  {
    name: "임소희",
    lastName: "",
    firstName: "",
    department: "미반영그룹",
    position: "0",
    yumId: "",
  },
  {
    name: "임승호",
    lastName: "Lim",
    firstName: "SeungHo",
    department: "직영본부 운영1팀 세종대",
    position: "점장",
    yumId: "MmH8636",
  },
  {
    name: "임용택",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "임인영",
    lastName: "",
    firstName: "",
    department: "HR본부 피플팀",
    position: "0",
    yumId: "XmB3825",
  },
  {
    name: "임재우",
    lastName: "Lim",
    firstName: "Jaewoo",
    department: "직영본부 운영1팀 천호역",
    position: "점장",
    yumId: "BmI3765",
  },
  {
    name: "임정연",
    lastName: "",
    firstName: "",
    department: "마케팅본부 브랜드MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "임채영",
    lastName: "임",
    firstName: "채영",
    department: "직영본부 운영3팀 평택",
    position: "부점장",
    yumId: "UmQ1883",
  },
  {
    name: "임채일",
    lastName: "Lim",
    firstName: "Chaeil",
    department: "직영본부 운영1팀 진접",
    position: "점장",
    yumId: "TmI1544",
  },
  {
    name: "임충열",
    lastName: "Lim",
    firstName: "Choongyeol",
    department: "직영본부 운영3팀 오산DT",
    position: "점장",
    yumId: "EmT7438",
  },
  {
    name: "장동필",
    lastName: "",
    firstName: "",
    department: "가맹본부  시설감리팀 영선파트",
    position: "0",
    yumId: "",
  },
  {
    name: "장동휘",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "장슬지",
    lastName: "Jang",
    firstName: "Seulji",
    department: "직영본부 운영3팀 은행동1",
    position: "점장",
    yumId: "OmN1111",
  },
  {
    name: "장영준",
    lastName: "",
    firstName: "",
    department: "마케팅본부 브랜드MKT팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "장영철",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 학동역2",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "장영화",
    lastName: "Jang",
    firstName: "Younghwa",
    department: "직영본부 운영1팀",
    position: "Area Coach",
    yumId: "LbV8803",
  },
  {
    name: "장재석",
    lastName: "",
    firstName: "",
    department: "대외지원실",
    position: "0",
    yumId: "0",
  },
  {
    name: "장준영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 서울대입구역",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "장준혁",
    lastName: "Jang",
    firstName: "Junhyuk",
    department: "직영본부 운영1팀 용인수지",
    position: "부점장",
    yumId: "jbj9620",
  },
  {
    name: "장창명",
    lastName: "Jang",
    firstName: "Changmyun",
    department: "직영본부 운영3팀 광주충장로",
    position: "점장",
    yumId: "WmK7455",
  },
  {
    name: "장태원",
    lastName: "장",
    firstName: "태원",
    department: "직영본부 운영3팀 전북도청",
    position: "부점장",
    yumId: "YmR4415",
  },
  {
    name: "장한별",
    lastName: "장",
    firstName: "한별",
    department: "직영본부 운영2팀 인천구월",
    position: "부점장",
    yumId: "SmM2485",
  },
  {
    name: "장현정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 충무로역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "전성균",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 서초우성",
    position: "QL",
    yumId: "",
  },
  {
    name: "전수현",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀",
    position: "0",
    yumId: "",
  },
  {
    name: "전영욱",
    lastName: "",
    firstName: "",
    department: "마케팅본부 FIT팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "전은미",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 영등포역",
    position: "QL",
    yumId: "IuG4961",
  },
  {
    name: "전은혜",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "전재두",
    lastName: "Jeon",
    firstName: "Jaedoo",
    department: "직영본부 운영2팀 왕십리역사",
    position: "부점장",
    yumId: "jbj1116",
  },
  {
    name: "전재현",
    lastName: "전",
    firstName: "재현",
    department: "직영본부 운영1팀 창동역",
    position: "부점장",
    yumId: "DmB2515",
  },
  {
    name: "전종원",
    lastName: "전",
    firstName: "종원",
    department: "직영본부 운영1팀 중계은행사거리",
    position: "부점장",
    yumId: "EmL2988",
  },
  {
    name: "전준성",
    lastName: "Jeon",
    firstName: "Junsung",
    department: "직영본부 운영3팀 창원상남동",
    position: "점장",
    yumId: "KmQ2198",
  },
  {
    name: "전현주",
    lastName: "Jun",
    firstName: "Hyunjoo",
    department: "직영본부 운영2팀 여의도",
    position: "부점장",
    yumId: "hbj4861",
  },
  {
    name: "전희진",
    lastName: "Jeon",
    firstName: "Huijin",
    department: "직영본부 운영3팀",
    position: "Area Coach",
    yumId: "ddy7755",
  },
  {
    name: "정강채",
    lastName: "Jeong",
    firstName: "Kangchae",
    department: "직영본부 운영1팀 용인상현",
    position: "부점장",
    yumId: "kbj5676",
  },
  {
    name: "정경희",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 영등포역",
    position: "QL",
    yumId: "NuU4304",
  },
  {
    name: "정다슬",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 중앙대",
    position: "QL",
    yumId: "",
  },
  {
    name: "정다은",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 상인네거리",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "정다혜",
    lastName: "Jeong",
    firstName: "Dahye",
    department: "직영본부 운영2팀 응암",
    position: "점장",
    yumId: "QuV5628",
  },
  {
    name: "정민규",
    lastName: "Jeong",
    firstName: "Mingyu",
    department: "직영본부 운영3팀 울산현대",
    position: "점장",
    yumId: "mbj7456",
  },
  {
    name: "정상진",
    lastName: "Jeong",
    firstName: "Sangjin",
    department: "직영본부 운영1팀 석계역",
    position: "점장",
    yumId: "VmJ1135",
  },
  {
    name: "정석균",
    lastName: "Jeong",
    firstName: "Seoukkyun",
    department: "직영본부 운영3팀",
    position: "Area Coach",
    yumId: "sdj5623",
  },
  {
    name: "정소리",
    lastName: "Jeong",
    firstName: "Sori",
    department: "직영본부 운영2팀 한국외대",
    position: "점장",
    yumId: "DmI9495",
  },
  {
    name: "정순영",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 부산장산역",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "정영식",
    lastName: "",
    firstName: "",
    department: "직영본부 운영전략팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "정용운",
    lastName: "Jung",
    firstName: "Yongwoon",
    department: "가맹본부 가맹운영팀",
    position: "Area Coach",
    yumId: "yyj8830",
  },
  {
    name: "정우림",
    lastName: "정",
    firstName: "우림",
    department: "직영본부 운영2팀 상암DMC",
    position: "부점장",
    yumId: "NmQ3567",
  },
  {
    name: "정우준",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "정원길",
    lastName: "Jeong",
    firstName: "Wongil",
    department: "직영본부 운영2팀 파주문산",
    position: "점장",
    yumId: "DmW4825",
  },
  {
    name: "정윤훈",
    lastName: "Jeong",
    firstName: "Yoonhoon",
    department: "직영본부 운영1팀 미사역",
    position: "점장",
    yumId: "QmE1623",
  },
  {
    name: "정의정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 강남고속터미널",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "정재이",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 위례중앙",
    position: "QL",
    yumId: "",
  },
  {
    name: "정준혁",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "정창하",
    lastName: "정",
    firstName: "창하",
    department: "직영본부 운영2팀 홍익대",
    position: "부점장",
    yumId: "OmU3507",
  },
  {
    name: "정현주",
    lastName: "Jeong",
    firstName: "Hyeonju",
    department: "직영본부 운영2팀 명지대",
    position: "점장",
    yumId: "XmE6850",
  },
  {
    name: "정현지",
    lastName: "정",
    firstName: "현지",
    department: "직영본부 운영3팀 울산현대",
    position: "부점장",
    yumId: "NmX6100",
  },
  {
    name: "정형상",
    lastName: "Jeong",
    firstName: "Hyunsang",
    department: "직영본부 운영3팀 제주서귀포DI",
    position: "점장",
    yumId: "YmU8576",
  },
  {
    name: "정혜린",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "QL수습",
    yumId: "0",
  },
  {
    name: "정혜지",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 부산서면",
    position: "QL",
    yumId: "",
  },
  {
    name: "조경희",
    lastName: "Jo",
    firstName: "Kyunghee",
    department: "직영본부 운영1팀 월계이마트",
    position: "부점장",
    yumId: "kbj5412",
  },
  {
    name: "조기윤",
    lastName: "Jo",
    firstName: "Kiyoon",
    department: "직영본부 운영3팀",
    position: "Area Coach",
    yumId: "PmJ2584",
  },
  {
    name: "조나현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 은행동1",
    position: "부점장",
    yumId: "",
  },
  {
    name: "조대웅",
    lastName: "Jo",
    firstName: "Daewoong",
    department: "직영본부 운영1팀 용인에버랜드",
    position: "부점장",
    yumId: "dbj9100",
  },
  {
    name: "조미정",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 대전시청역",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "조보배",
    lastName: "Jo",
    firstName: "Bobae",
    department: "직영본부 운영1팀 신사역",
    position: "점장",
    yumId: "ImK3790",
  },
  {
    name: "조성미",
    lastName: "",
    firstName: "",
    department: "미반영그룹",
    position: "0",
    yumId: "QuO3092",
  },
  {
    name: "조성민",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "조성철",
    lastName: "",
    firstName: "",
    department: "HR본부 피플팀",
    position: "0",
    yumId: "",
  },
  {
    name: "조소연",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "0",
  },
  {
    name: "조승아",
    lastName: "",
    firstName: "",
    department: "HR본부 피플팀",
    position: "0",
    yumId: "",
  },
  {
    name: "조승환",
    lastName: "Jo",
    firstName: "SeungHwan",
    department: "직영본부 운영2팀 사당역",
    position: "점장",
    yumId: "SmH8634",
  },
  {
    name: "조영래",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "조용원",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 부천역",
    position: "QL",
    yumId: "DuH4130",
  },
  {
    name: "조용일",
    lastName: "조",
    firstName: "용일",
    department: "직영본부 운영3팀 대구문화동",
    position: "부점장",
    yumId: "OmG2017",
  },
  {
    name: "조원식",
    lastName: "Jo",
    firstName: "WonSik",
    department: "직영본부 운영3팀 대전시청역",
    position: "점장",
    yumId: "KmL8220",
  },
  {
    name: "조원호",
    lastName: "조",
    firstName: "원호",
    department: "직영본부 운영2팀 동대문",
    position: "부점장",
    yumId: "MmT6432",
  },
  {
    name: "조유정",
    lastName: "조",
    firstName: "유정",
    department: "직영본부 운영3팀 대구문화동",
    position: "부점장",
    yumId: "CmK7477",
  },
  {
    name: "조은샘",
    lastName: "",
    firstName: "",
    department: "마케팅본부 브랜드MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "조정원",
    lastName: "조",
    firstName: "정원",
    department: "직영본부 운영1팀 먹골역",
    position: "부점장",
    yumId: "QmQ4910",
  },
  {
    name: "조정은",
    lastName: "조",
    firstName: "정은",
    department: "직영본부 운영1팀 철산역",
    position: "부점장",
    yumId: "LmN3848",
  },
  {
    name: "조한근",
    lastName: "Jo",
    firstName: "Hangeun",
    department: "직영본부 운영1팀 용인에버랜드",
    position: "점장",
    yumId: "SmD1294",
  },
  {
    name: "조혜연",
    lastName: "Jo",
    firstName: "Hyeyeon",
    department: "직영본부 운영1팀 잠실롯데월드",
    position: "부점장",
    yumId: "hbj3700",
  },
  {
    name: "조효린",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "주재명",
    lastName: "Ju",
    firstName: "Jaemyoung",
    department: "직영본부 운영1팀 강남역",
    position: "부점장",
    yumId: "jbj2193",
  },
  {
    name: "주현욱",
    lastName: "Joo",
    firstName: "Hyunwook",
    department: "직영본부 운영1팀 수원인계DT",
    position: "부점장",
    yumId: "hbj3783",
  },
  {
    name: "진달래",
    lastName: "JIN",
    firstName: "DALRAE",
    department: "직영본부 운영3팀",
    position: "Area Coach",
    yumId: "dfj3653",
  },
  {
    name: "진동하",
    lastName: "Jin",
    firstName: "Dongha",
    department: "직영본부 운영3팀 유성온천",
    position: "점장",
    yumId: "RmO1160",
  },
  {
    name: "진선영",
    lastName: "jin",
    firstName: "sunyoung",
    department: "직영본부 운영2팀",
    position: "Area Coach",
    yumId: "EbA9426",
  },
  {
    name: "진승호",
    lastName: "",
    firstName: "",
    department: "가맹본부  개발2팀",
    position: "0",
    yumId: "",
  },
  {
    name: "차상만",
    lastName: "차",
    firstName: "상만",
    department: "직영본부 운영2팀 노량진역",
    position: "부점장",
    yumId: "HmE8451",
  },
  {
    name: "차승길",
    lastName: "차",
    firstName: "승길",
    department: "직영본부 운영2팀 상암DMC",
    position: "부점장",
    yumId: "TmR6581",
  },
  {
    name: "채윤아",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 당진",
    position: "QL",
    yumId: "0",
  },
  {
    name: "채은교",
    lastName: "Chae",
    firstName: "Eungyo",
    department: "직영본부 운영2팀 보라매",
    position: "부점장",
    yumId: "ekc6670",
  },
  {
    name: "채주희",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 숙대입구",
    position: "QL",
    yumId: "",
  },
  {
    name: "채지수",
    lastName: "Chae",
    firstName: "Jisu",
    department: "직영본부 운영3팀 광주수완",
    position: "부점장",
    yumId: "jbc9511",
  },
  {
    name: "채효근",
    lastName: "Chae",
    firstName: "Hyokeun",
    department: "직영본부 운영3팀 노은역",
    position: "점장",
    yumId: "hdc8898",
  },
  {
    name: "천민재",
    lastName: "",
    firstName: "",
    department: "마케팅본부 플랫폼MKT팀",
    position: "팀장",
    yumId: "",
  },
  {
    name: "천세은",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 봉천역",
    position: "점장",
    yumId: "PmW4344",
  },
  {
    name: "최민석",
    lastName: "Choi",
    firstName: "Minseok",
    department: "직영본부 운영1팀 창동역",
    position: "부점장",
    yumId: "mbc9157",
  },
  {
    name: "최부권",
    lastName: "Choi",
    firstName: "Bugwon",
    department: "직영본부 운영2팀 발산역",
    position: "부점장",
    yumId: "bbc9498",
  },
  {
    name: "최서연",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 청주사창사거리",
    position: "부점장",
    yumId: "OmB2466sic2117",
  },
  {
    name: "최석현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 이수역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "최성현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 당산역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "최소라",
    lastName: "Choi",
    firstName: "Sora",
    department: "직영본부 운영3팀 전주송천",
    position: "점장",
    yumId: "FmC5904",
  },
  {
    name: "최송희",
    lastName: "최",
    firstName: "송희",
    department: "직영본부 운영2팀 돈암동1",
    position: "부점장",
    yumId: "GmY5206",
  },
  {
    name: "최수경",
    lastName: "Choi",
    firstName: "Sookyung",
    department: "직영본부 운영1팀 안산선부",
    position: "점장",
    yumId: "ImJ2573",
  },
  {
    name: "최영훈",
    lastName: "",
    firstName: "",
    department: "HR본부 EHS팀",
    position: "0",
    yumId: "",
  },
  {
    name: "최요셉",
    lastName: "Choi",
    firstName: "Yoseb",
    department: "직영본부 운영1팀 수원역사1",
    position: "부점장",
    yumId: "ybc6278",
  },
  {
    name: "최윤아",
    lastName: "Choi",
    firstName: "Yoonah",
    department: "직영본부 운영2팀 독산동",
    position: "점장",
    yumId: "GmO5330",
  },
  {
    name: "최은미",
    lastName: "최",
    firstName: "은미",
    department: "직영본부 운영1팀",
    position: "Area Coach",
    yumId: "QmC3632",
  },
  {
    name: "최은지",
    lastName: "최",
    firstName: "은지",
    department: "직영본부 운영3팀 부산구서DT",
    position: "점장",
    yumId: "TmQ1500",
  },
  {
    name: "최인수",
    lastName: "최",
    firstName: "인수",
    department: "직영본부 운영2팀 인하대",
    position: "점장",
    yumId: "LmT2828",
  },
  {
    name: "최인원",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 서울대입구역",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "최정우",
    lastName: "최",
    firstName: "정우",
    department: "직영본부 운영1팀 서울교대S",
    position: "부점장",
    yumId: "EmF1181",
  },
  {
    name: "최종범",
    lastName: "Choi",
    firstName: "Jongbum",
    department: "직영본부 운영2팀 서울대입구역",
    position: "점장",
    yumId: "HmS6649",
  },
  {
    name: "최주영",
    lastName: "Choi",
    firstName: "Jooyoung",
    department: "직영본부 운영3팀 내당동",
    position: "점장",
    yumId: "MmJ3193",
  },
  {
    name: "최지민",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 서현역",
    position: "QL",
    yumId: "",
  },
  {
    name: "최지현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 광주터미널유스퀘어",
    position: "부점장",
    yumId: "",
  },
  {
    name: "최진호",
    lastName: "",
    firstName: "",
    department: "HR본부 교육팀 (교육)",
    position: "부점장",
    yumId: "",
  },
  {
    name: "최철민",
    lastName: "Choi",
    firstName: "Cheolmin",
    department: "직영본부 운영2팀 화정",
    position: "부점장",
    yumId: "cbc9929",
  },
  {
    name: "최하늬",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "",
  },
  {
    name: "최현아",
    lastName: "Choi",
    firstName: "Hyunah",
    department: "직영본부 운영2팀 봉천역",
    position: "부점장",
    yumId: "hbc7462",
  },
  {
    name: "최형우",
    lastName: "최",
    firstName: "형우",
    department: "직영본부 운영2팀 한남순천향",
    position: "점장",
    yumId: "HmQ4303",
  },
  {
    name: "최형진",
    lastName: "Choi",
    firstName: "Hyungjin",
    department: "직영본부 운영1팀 명일DI",
    position: "점장",
    yumId: "NmS1650",
  },
  {
    name: "최효권",
    lastName: "최",
    firstName: "효권",
    department: "직영본부 운영1팀 용인보정",
    position: "부점장",
    yumId: "CmH3886",
  },
  {
    name: "최희원",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인천논현",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "편승호",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 포항터미널",
    position: "부점장",
    yumId: "KuJ1772",
  },
  {
    name: "표은수",
    lastName: "Pyo",
    firstName: "Eunsu",
    department: "직영본부 운영2팀 인천스퀘어원",
    position: "점장",
    yumId: "XmA2700",
  },
  {
    name: "하석현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 부산구서DT",
    position: "QL",
    yumId: "",
  },
  {
    name: "하원희",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 천호역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "하지수",
    lastName: "Ha",
    firstName: "Jisoo",
    department: "직영본부 운영2팀 광화문",
    position: "점장",
    yumId: "CmF5250",
  },
  {
    name: "한솔",
    lastName: "한",
    firstName: "솔",
    department: "직영본부 운영1팀 안산선부",
    position: "부점장",
    yumId: "OmE6471",
  },
  {
    name: "한수진",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 마두역",
    position: "부점장",
    yumId: "",
  },
  {
    name: "한시현",
    lastName: "한",
    firstName: "시현",
    department: "직영본부 운영2팀 파주운정DI",
    position: "부점장",
    yumId: "WbJ5399",
  },
  {
    name: "한영선",
    lastName: "Han",
    firstName: "Youngsun",
    department: "직영본부 운영2팀 인천송도",
    position: "점장",
    yumId: "YmH5963",
  },
  {
    name: "한준수",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 청주사창사거리",
    position: "QL",
    yumId: "",
  },
  {
    name: "한지형",
    lastName: "",
    firstName: "",
    department: "경영본부 재무팀",
    position: "0",
    yumId: "",
  },
  {
    name: "한창화",
    lastName: "Han",
    firstName: "Changhwa",
    department: "직영본부 운영3팀 광주용봉DT",
    position: "점장",
    yumId: "FmM8446",
  },
  {
    name: "함승주",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 안양일번가",
    position: "부점장",
    yumId: "",
  },
  {
    name: "허진영",
    lastName: "Heo",
    firstName: "Jinyoung",
    department: "직영본부 운영2팀 연신내역",
    position: "부점장",
    yumId: "jbh6881",
  },
  {
    name: "현동준",
    lastName: "",
    firstName: "",
    department: "마케팅본부 플랫폼MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "현주",
    lastName: "Hyun",
    firstName: "Joo",
    department: "직영본부 운영2팀 마두역",
    position: "점장",
    yumId: "UmY1602",
  },
  {
    name: "현진숙",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 인하대",
    position: "부점장",
    yumId: "",
  },
  {
    name: "형광례",
    lastName: "형",
    firstName: "광례",
    department: "직영본부 운영1팀 코엑스mall",
    position: "부점장",
    yumId: "AmU4308",
  },
  {
    name: "호현경",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 대학로",
    position: "부점장",
    yumId: "",
  },
  {
    name: "홍기범",
    lastName: "홍",
    firstName: "기범",
    department: "직영본부 운영1팀 대치동",
    position: "부점장",
    yumId: "FmV9739",
  },
  {
    name: "홍상현",
    lastName: "",
    firstName: "",
    department: "마케팅본부 브랜드MKT팀",
    position: "0",
    yumId: "",
  },
  {
    name: "홍성국",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 광주용봉DT",
    position: "부점장",
    yumId: "0",
  },
  {
    name: "홍성수",
    lastName: "홍",
    firstName: "성수",
    department: "직영본부 운영2팀 가산디지털",
    position: "부점장",
    yumId: "ImB5736",
  },
  {
    name: "홍아름",
    lastName: "HONG",
    firstName: "Ahreum",
    department: "직영본부 운영1팀",
    position: "Area Coach",
    yumId: "EbK3269",
  },
  {
    name: "홍원표",
    lastName: "Hong",
    firstName: "Wonpyo",
    department: "직영본부 운영2팀",
    position: "Area Coach",
    yumId: "wyh7652",
  },
  {
    name: "홍윤기",
    lastName: "홍",
    firstName: "윤기",
    department: "직영본부 운영2팀 홍익대",
    position: "부점장",
    yumId: "NmJ1455",
  },
  {
    name: "홍준혁",
    lastName: "",
    firstName: "",
    department: "직영본부 운영1팀 용인에버랜드",
    position: "부점장",
    yumId: "",
  },
  {
    name: "황서진",
    lastName: "",
    firstName: "",
    department: "직영본부 운영3팀 창원더시티세븐",
    position: "부점장",
    yumId: "",
  },
  {
    name: "황세현",
    lastName: "",
    firstName: "",
    department: "직영본부 운영2팀 파주금촌",
    position: "부점장",
    yumId: "MuY7671",
  },
  {
    name: "황정경",
    lastName: "",
    firstName: "",
    department: "가맹본부 가맹운영팀",
    position: "팀장",
    yumId: "0",
  },
];

function Employee({ name, lastName, firstName, department, position, yumId }) {
  return (
    <tr>
      <td>{name}</td>
      <td>{lastName}</td>
      <td>{firstName}</td>
      <td>{department}</td>
      <td>{position}</td>
      <td>{yumId}</td>
    </tr>
  );
}

function filterEmployee(name, position) {
  const filterName = name.toUpperCase();
  const filterPosition = position.toUpperCase();

  if (filterPosition === "") {
    return employeeData.filter((employee) => employee.name === filterName);
  }

  return employeeData.filter(
    (employee) =>
      employee.name === filterName && employee.position === filterPosition
  );
}

export default function List() {
  const [employees, setEmployees] = useState(null);
  const [searchName, setSearchName] = useState("");
  const [searchPosition, setSearchPosition] = useState("");

  function handleClick() {
    const filteredEmployees = filterEmployee(searchName, searchPosition);
    setEmployees(filteredEmployees);
  }

  function handleKeydown(event) {
    if (event.key === "Enter") {
      handleClick();
      return;
    }
  }

  return (
    <div className={classes.container}>
      <h1 className={classes.title}>KFC 직원 정보</h1>

      <input
        type="text"
        placeholder="이름을 검색하세요..."
        className={classes.input}
        value={searchName}
        onChange={(event) => setSearchName(event.target.value)}
        onKeyDown={handleKeydown}
      />
      <select
        className={classes.input}
        value={searchPosition}
        onChange={(event) => setSearchPosition(event.target.value)}
      >
        <option value="">전체 직책</option>
        <option value="점장">점장</option>
        <option value="부점장">부점장</option>
        <option value="사원">사원</option>
        <option value="QL">QL</option>
      </select>

      <button type="button" className={classes.button} onClick={handleClick}>
        검색
      </button>

      <table id="employeeTable">
        <thead>
          <tr>
            <th>이름</th>
            <th>영문(성)</th>
            <th>영문(이름)</th>
            <th>소속명</th>
            <th>직책</th>
            <th>YUM ID</th>
          </tr>
        </thead>
        <tbody>
          {employees !== null &&
            employees.map((employee) => (
              <Employee key={employee.yumId} {...employee} />
            ))}
        </tbody>
      </table>
      {employees && employees.length === 0 && (
        <h2 style={{ textAlign: "center", color: "#BF360C" }}>
          검색 결과가 없습니다.
        </h2>
      )}
    </div>
  );
}
